version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - pwd
      - make lambdas
      - cd lambdas
      - cd get-input-files
      - zip ../get-input-files.zip index.js package.json node_modules/**/*
      - cd ..
      - cd format-chunk
      - zip ../format-chunk.zip index.js package.json node_modules/**/*
      - cd ..
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing lambda function update... 
      - aws lambda update-function-code --function-name transcoding-api-get-input-files-w9gxhplj7q9mju3h  --zip-file fileb://./get-input-files.zip
      - aws lambda publish-version --function-name transcoding-api-get-input-files-w9gxhplj7q9mju3h
      - aws lambda update-function-code --function-name transcoding-api-format-chunk-w9gxhplj7q9mju3h  --zip-file fileb://./format-chunk.zip
      - aws lambda publish-version --function-name transcoding-api-format-chunk-w9gxhplj7q9mju3h